### ISSUE TITLE
Reproducing Schreiber's article using PyCausality

### ISSUE THREAD

**Issue by mghadam** [ZacKeskin/PyCausality#4]
I'm trying to reproduce Example 3 in Schreiber 2000's seminal article using PyCausality [here](https://colab.research.google.com/drive/1OIJL3ejEwRFnAamcH48UGK82RdcRnTid?usp=sharing).

![image](https://user-images.githubusercontent.com/10244293/99901383-95e92580-2ccb-11eb-92d1-de4d3919748c.png)

I wonder if it is possible at all to reproduce such results with PyCausality and get the same TE numbers to reproduce the figure in question?

**Comment by ZacKeskin** [comment]
Sorry for the delay in responding to this; I had a quick look at the plot, it looks pretty comparable to me.

Schreiber uses a slightly different computational approach than in PyCausality (this is expected, and in many ways, the differentiator in causal signal detection is how you perform the nonparametric density estimation). 

The numbers will not be the exact same as Schreiber without using the exact same pre-processing and density estimation steps.
